{% set name = "sacc" %}
{% set version = "0.4.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LSSTDESC/sacc/archive/{{ version }}.tar.gz
  sha256: ef0a12ac8215b105743e651f38394e9f590c7a876b6e8758449fc54a5036949b

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - astropy
    - scipy
    - numpy
    - numpydoc

test:
  imports:
    - sacc

about:
  home: https://github.com/LSSTDESC/sacc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Save All Correlations and Covariances

extra:
  recipe-maintainers:
    - beckermr
